// === 64 QUẺ KINH DỊCH — BÁT QUÁI + LUẬN GIẢI TIẾNG VIỆT ===

export const BAT_QUAI = [
  { id: 0, nameVN: 'Càn',  nameHV: '乾', element: 'Kim',  direction: 'Tây Bắc', image: '☰', meaning: 'Trời — sáng tạo, sức mạnh, khởi nguồn' },
  { id: 1, nameVN: 'Đoài', nameHV: '兑', element: 'Kim',  direction: 'Tây',     image: '☱', meaning: 'Hồ — vui vẻ, thu hút, giao tiếp' },
  { id: 2, nameVN: 'Ly',   nameHV: '离', element: 'Hỏa',  direction: 'Nam',     image: '☲', meaning: 'Lửa — ánh sáng, trí tuệ, sáng suốt' },
  { id: 3, nameVN: 'Chấn', nameHV: '震', element: 'Mộc',  direction: 'Đông',    image: '☳', meaning: 'Sấm — hành động, thức tỉnh, biến động' },
  { id: 4, nameVN: 'Tốn',  nameHV: '巽', element: 'Mộc',  direction: 'Đông Nam',image: '☴', meaning: 'Gió — thâm nhập, mềm dẻo, lan tỏa' },
  { id: 5, nameVN: 'Khảm', nameHV: '坎', element: 'Thủy', direction: 'Bắc',     image: '☵', meaning: 'Nước — nguy hiểm, trí tuệ, thích nghi' },
  { id: 6, nameVN: 'Cấn',  nameHV: '艮', element: 'Thổ',  direction: 'Đông Bắc',image: '☶', meaning: 'Núi — vững chãi, ngăn cản, tĩnh lặng' },
  { id: 7, nameVN: 'Khôn', nameHV: '坤', element: 'Thổ',  direction: 'Tây Nam', image: '☷', meaning: 'Đất — nuôi dưỡng, bao dung, thuận hòa' },
];

const TRIGRAM_LINES = [
  [1, 1, 1], // 0 Càn
  [0, 1, 1], // 1 Đoài
  [1, 0, 1], // 2 Ly
  [0, 0, 1], // 3 Chấn
  [1, 1, 0], // 4 Tốn
  [0, 1, 0], // 5 Khảm
  [1, 0, 0], // 6 Cấn
  [0, 0, 0], // 7 Khôn
];

// ─── 64 QUẺ DỊCH ───
export const QUE_64 = [
  { number: 1, nameVN: 'Thuần Càn', nameHV: '乾', upper: 0, lower: 0, lines: [1, 1, 1, 1, 1, 1],
    meaning: 'Quẻ Thuần Càn là quẻ số 1 trong Kinh Dịch, tượng trưng cho Trời, cho sức mạnh sáng tạo vô biên. Càn là khởi nguyên của vạn vật, là năng lượng dương thuần khiết. Đây là quẻ Đại Cát, báo hiệu thời kỳ hoàng kim, mọi sự hanh thông.',
    career: 'Công danh hiển đạt, thăng tiến vượt bậc. Thời điểm vàng để khởi nghiệp, mở rộng kinh doanh. Sự nghiệp như rồng gặp mây. Hợp với vai trò lãnh đạo.',
    love: 'Tình duyên viên mãn, tìm được tri kỷ. Hai người hiểu nhau sâu sắc, cùng phát triển. Hôn nhân bền chặt.',
    finance: 'Tài lộc dồi dào, tiền vào như nước. Đầu tư sinh lời, cơ hội làm giàu từ nhiều hướng.',
    health: 'Sức khỏe sung mãn, tinh thần minh mẫn. Không bệnh tật, thân tâm an lạc.',
    advice: 'Hãy tự tin hành động, phát huy hết tài năng. Giữ vững đạo đức, công bằng. Đừng để quyền lực làm hỏng tâm tính.' },
  { number: 2, nameVN: 'Thuần Khôn', nameHV: '坤', upper: 7, lower: 7, lines: [0, 0, 0, 0, 0, 0],
    meaning: 'Quẻ Thuần Khôn tượng trưng cho Đất, cho sự bao dung và nuôi dưỡng. Khôn là âm nhu thuần khiết, là mẹ của muôn loài. Quẻ dạy về đức khiêm hạ, nhẫn nại, phục tùng quy luật tự nhiên.',
    career: 'Hợp làm việc hậu thuẫn, hỗ trợ, quản lý. Không nên đứng mũi chịu sào. Thành công đến từ sự kiên trì.',
    love: 'Tình yêu bền vững, sâu sắc ít sóng gió. Gia đạo yên ấm, hòa thuận.',
    finance: 'Tài chính ổn định. Tiền bạc đến từ sự chăm chỉ. Nên đầu tư dài hạn, an toàn.',
    health: 'Sức khỏe tốt, chú ý hệ tiêu hóa và xương khớp. Duy trì sinh hoạt điều độ.',
    advice: 'Hãy khiêm tốn và bao dung. Học từ thiên nhiên: im lặng mà nuôi dưỡng vạn vật.' },
  { number: 3, nameVN: 'Thủy Lôi Truân', nameHV: '屯', upper: 5, lower: 3, lines: [0, 0, 1, 0, 1, 0],
    meaning: 'Quẻ Truân tượng trưng cho sự khó khăn buổi ban đầu. Mây che trời, sấm động dưới thấp. Mưa chưa đổ, vạn vật chưa sinh. Nhưng khó khăn chỉ là tạm thời.',
    career: 'Khởi đầu khó khăn, trắc trở. Cần kiên nhẫn vượt qua. Đừng nản chí, cơ hội đang đến.',
    love: 'Tình yêu giai đoạn đầu còn nhiều thử thách. Cả hai cần kiên nhẫn và thấu hiểu.',
    finance: 'Tài chính eo hẹp. Chưa nên đầu tư lớn. Tiết kiệm và chờ thời cơ.',
    health: 'Sức khỏe yếu, dễ bệnh vặt. Cần nghỉ ngơi, bồi bổ.',
    advice: 'Kiên nhẫn vượt qua giai đoạn khó khăn. Mọi khởi đầu đều gian nan nhưng sẽ sáng sủa.' },
  { number: 4, nameVN: 'Sơn Thủy Mông', nameHV: '蒙', upper: 6, lower: 5, lines: [0, 1, 0, 1, 0, 0],
    meaning: 'Quẻ Mông tượng trưng cho tuổi trẻ, sự mờ mịt cần khai sáng. Núi chặn dòng nước, tượng trưng cho trở ngại cần vượt qua.',
    career: 'Cần học hỏi, trau dồi kiến thức. Chưa vội hành động. Tìm thầy, tìm bạn đồng hành.',
    love: 'Tình yêu non trẻ, cần thời gian tìm hiểu. Đừng vội vàng quyết định.',
    finance: 'Chưa nên đầu tư. Học cách quản lý tiền bạc trước đã.',
    health: 'Sức khỏe bình thường. Có thể gặp vấn đề về tai mũi họng.',
    advice: 'Hãy khiêm tốn học hỏi. Ai không biết mà tự cho mình biết là kẻ ngu. Ai biết mình không biết là người khôn.' },
  { number: 5, nameVN: 'Thủy Thiên Nhu', nameHV: '需', upper: 5, lower: 0, lines: [1, 1, 1, 0, 1, 0],
    meaning: 'Quẻ Nhu tượng trưng cho sự chờ đợi. Mây trên trời, mưa chưa đổ. Cần kiên nhẫn chờ thời cơ chín muồi.',
    career: 'Cần chờ đợi, đừng nóng vội. Cơ hội sẽ đến với người biết kiên nhẫn. Chuẩn bị sẵn sàng.',
    love: 'Tình duyên chưa tới, hãy chờ đợi người phù hợp. Ép dầu ép mỡ ai nỡ ép duyên.',
    finance: 'Chưa phải thời điểm đầu tư. Giữ tiền chờ cơ hội tốt hơn.',
    health: 'Sức khỏe ổn định. Giữ tinh thần thoải mái, đừng lo lắng thái quá.',
    advice: 'Biết chờ đợi là một nghệ thuật. Trời không phụ lòng người biết kiên nhẫn.' },
  { number: 6, nameVN: 'Thiên Thủy Tụng', nameHV: '訟', upper: 0, lower: 5, lines: [0, 1, 0, 1, 1, 1],
    meaning: 'Quẻ Tụng tượng trưng cho tranh chấp, kiện tụng. Trời ngược nước, không hòa hợp. Nên tránh xung đột.',
    career: 'Có tranh chấp trong công việc. Nên hòa giải, tránh kiện tụng. Tìm người trung gian hòa giải.',
    love: 'Mâu thuẫn trong tình cảm. Cả hai cần bình tĩnh nói chuyện, tránh đổ lỗi.',
    finance: 'Tranh chấp tiền bạc. Nên minh bạch mọi giao dịch. Tránh cho vay mượn.',
    health: 'Dễ căng thẳng, huyết áp cao. Cần thư giãn, tránh stress.',
    advice: 'Tốt nhất là tránh tranh chấp. Hòa cả làng. Một sự nhịn là chín sự lành.' },
  { number: 7, nameVN: 'Địa Thủy Sư', nameHV: '師', upper: 7, lower: 5, lines: [0, 1, 0, 0, 0, 0],
    meaning: 'Quẻ Sư tượng trưng cho quân đội, sự lãnh đạo tập thể. Đất chứa nước, tượng trưng cho sức mạnh quần chúng.',
    career: 'Lãnh đạo tốt, tập hợp được người tài. Hợp với vai trò chỉ huy, quản lý dự án nhóm.',
    love: 'Tình yêu có sự dẫn dắt, người chủ động vai trò chính.',
    finance: 'Hợp tác làm ăn tốt. Nên đầu tư theo nhóm, không nên một mình.',
    health: 'Sức khỏe tốt khi có người đồng hành. Tránh cô đơn.',
    advice: 'Đoàn kết là sức mạnh. Tìm đồng đội tốt, lãnh đạo bằng nhân đức.' },
  { number: 8, nameVN: 'Thủy Địa Tỷ', nameHV: '比', upper: 5, lower: 7, lines: [0, 0, 0, 0, 1, 0],
    meaning: 'Quẻ Tỷ tượng trưng cho sự gắn kết, thân thiện. Nước trên đất, thấm vào nhau, hòa hợp, đoàn kết.',
    career: 'Hợp tác tốt, đồng nghiệp hòa thuận. Xây dựng mối quan hệ bền vững.',
    love: 'Tình yêu hòa hợp, gắn bó. Hai người như nước với đất, không thể tách rời.',
    finance: 'Đầu tư cùng người tin cậy. Lợi nhuận từ sự hợp tác.',
    health: 'Tinh thần vui vẻ, sức khỏe tốt nhờ các mối quan hệ xã hội.',
    advice: 'Hãy xây dựng các mối quan hệ tốt đẹp. Đoàn kết tạo nên sức mạnh.' },
  { number: 9, nameVN: 'Phong Thiên Tiểu Súc', nameHV: '小畜', upper: 4, lower: 0, lines: [1, 1, 1, 1, 1, 0],
    meaning: 'Quẻ Tiểu Súc tượng trưng cho sự tích lũy nhỏ. Gió trên trời, chưa đủ mạnh. Tích tiểu thành đại.',
    career: 'Tiến triển chậm nhưng chắc. Tích lũy kinh nghiệm, tài nguyên. Chưa phải bứt phá.',
    love: 'Tình cảm còn nhỏ bé, cần vun đắp từ từ. Đừng vội vàng.',
    finance: 'Tiết kiệm từng đồng. Đầu tư nhỏ, an toàn. Tích lũy dần.',
    health: 'Sức khỏe ổn. Chăm sóc cơ thể hàng ngày, đừng đợi bệnh mới chữa.',
    advice: 'Góp gió thành bão. Mọi việc lớn đều bắt đầu từ những điều nhỏ bé.' },
  { number: 10, nameVN: 'Thiên Trạch Lý', nameHV: '履', upper: 0, lower: 1, lines: [0, 1, 1, 1, 1, 1],
    meaning: 'Quẻ Lý tượng trưng cho việc thực hành, bước đi cẩn trọng. Trời trên đầm lầy, bước đi phải thận trọng kẻo sa lầy.',
    career: 'Tiến thận trọng từng bước. Nên theo kế hoạch, đừng liều lĩnh. Giữ vững kỷ cương.',
    love: 'Tình yêu cần sự tế nhị và cẩn trọng. Đừng để cảm xúc lấn át lý trí.',
    finance: 'Đầu tư an toàn. Kiểm tra kỹ trước khi quyết định.',
    health: 'Cẩn thận tai nạn khi di chuyển. Chú ý bước đi.',
    advice: 'Cẩn trọng từng bước, nhưng đừng để sợ hãi ngăn cản bước tiến.' },
  { number: 11, nameVN: 'Địa Thiên Thái', nameHV: '泰', upper: 7, lower: 0, lines: [1, 1, 1, 0, 0, 0],
    meaning: 'Quẻ Thái là một trong những quẻ tốt nhất. Đất trên trời, âm dương hòa hợp. Trời đất giao hòa, vạn vật thông suốt.',
    career: 'Mọi việc hanh thông, thăng tiến vượt bậc. Thời điểm vàng để khởi nghiệp, mở rộng.',
    love: 'Tình duyên như ý, hạnh phúc viên mãn. Kết hôn trong thời gian này rất tốt.',
    finance: 'Tài lộc dồi dào. Đầu tư đâu thắng đó. Mua bán thuận lợi.',
    health: 'Sức khỏe dồi dào, tinh thần sảng khoái. Đại cát cho mọi việc.',
    advice: 'Thái lai đây rồi! Hãy tận dụng thời vận tốt để làm những việc lớn.' },
  { number: 12, nameVN: 'Thiên Địa Bĩ', nameHV: '否', upper: 0, lower: 7, lines: [0, 0, 0, 1, 1, 1],
    meaning: 'Quẻ Bĩ tượng trưng cho sự bế tắc, trở ngại. Trời và đất không giao hòa. Mọi việc khó khăn, chờ thời cơ.',
    career: 'Khó khăn, bế tắc. Đừng cố gắng vào lúc này. Tốt nhất là giữ nguyên trạng, chờ thời.',
    love: 'Tình cảm gặp trở ngại, xa cách. Cần thời gian để hàn gắn.',
    finance: 'Suy thoái, thua lỗ. Tạm dừng đầu tư, bảo toàn vốn.',
    health: 'Bệnh tật, khó chịu. Nên đi khám và điều trị kịp thời.',
    advice: 'Đôi khi lùi một bước là tiến ba bước. Biết chờ đợi là khôn ngoan.' },
  { number: 13, nameVN: 'Thiên Hỏa Đồng Nhân', nameHV: '同人', upper: 0, lower: 2, lines: [1, 0, 1, 1, 1, 1],
    meaning: 'Quẻ Đồng Nhân tượng trưng cho sự hợp tác, đồng lòng. Lửa sáng trên trời, mọi người cùng nhìn thấy. Hợp tác công khai.',
    career: 'Hợp tác tốt, tìm được đồng nghiệp tâm đầu ý hợp. Dự án nhóm thành công.',
    love: 'Tình yêu từ tình bạn mà ra. Có sự đồng điệu về tâm hồn.',
    finance: 'Cùng đầu tư, cùng hưởng lợi. Hợp tác làm ăn với người tin cậy.',
    health: 'Sức khỏe tốt nhờ tinh thần lạc quan, yêu đời.',
    advice: 'Đồng lòng thì việc gì cũng xong. Tìm người cùng chí hướng để đồng hành.' },
  { number: 14, nameVN: 'Hỏa Thiên Đại Hữu', nameHV: '大有', upper: 2, lower: 0, lines: [1, 1, 1, 1, 0, 1],
    meaning: 'Quẻ Đại Hữu tượng trưng cho sự sở hữu lớn, giàu có. Lửa trên trời, chiếu sáng khắp nơi. Sở hữu nhiều của cải, địa vị.',
    career: 'Thăng tiến vượt bậc, đạt được thành tựu lớn. Công danh hiển hách. Mở rộng quyền lực.',
    love: 'Tình duyên tốt đẹp, có địa vị xã hội vững vàng.',
    finance: 'Đại tài, giàu có. Đầu tư sinh lời lớn. Của cải dồi dào.',
    health: 'Sức khỏe tốt, thân tâm an lạc. Hưởng thụ thành quả.',
    advice: 'Có của cải lớn, đừng quên chia sẻ với người khác. Hãy hào phóng.' },
  { number: 15, nameVN: 'Địa Sơn Khiêm', nameHV: '謙', upper: 7, lower: 6, lines: [1, 0, 0, 0, 0, 0],
    meaning: 'Quẻ Khiêm tượng trưng cho đức khiêm tốn. Núi cao mà nép mình dưới đất. Càng có tài càng khiêm hạ.',
    career: 'Thành công nhờ khiêm tốn, học hỏi. Sẽ được mọi người quý mến và giúp đỡ.',
    love: 'Tình yêu bền vững nhờ sự nhường nhịn, tôn trọng lẫn nhau.',
    finance: 'Tài chính ổn định. Giàu có nhờ sự chăm chỉ, không khoe khoang.',
    health: 'Sức khỏe điều độ, ít bệnh tật. Tinh thần an nhiên.',
    advice: 'Khiêm tốn là đức tính cao đẹp nhất. Càng thành công càng phải khiêm hạ.' },
  { number: 16, nameVN: 'Lôi Địa Dự', nameHV: '豫', upper: 3, lower: 7, lines: [0, 0, 0, 0, 0, 1],
    meaning: 'Quẻ Dự tượng trưng cho sự vui vẻ, chuẩn bị. Sấm động dưới đất, báo hiệu mùa xuân. Mọi người vui mừng, chuẩn bị cho tương lai.',
    career: 'Công việc thuận lợi, có sự chuẩn bị tốt. Lên kế hoạch kỹ càng.',
    love: 'Tình yêu vui vẻ, thoải mái. Chuẩn bị cho tương lai chung.',
    finance: 'Đầu tư có lợi nhuận. Nên chuẩn bị quỹ dự phòng.',
    health: 'Sức khỏe tốt, tinh thần phấn chấn.',
    advice: 'Chuẩn bị kỹ càng là chìa khóa thành công. Vui vẻ nhưng đừng quá lạc quan thái quá.' },
  { number: 17, nameVN: 'Trạch Lôi Tùy', nameHV: '隨', upper: 1, lower: 3, lines: [0, 0, 1, 0, 1, 1],
    meaning: 'Quẻ Tùy tượng trưng cho sự tùy thuận, theo đuổi. Sấm dưới đầm, nước theo sấm động. Tùy thời, tùy thế mà hành động.',
    career: 'Nên theo đuổi xu hướng mới. Thích ứng linh hoạt. Biết thời thế, thuận theo dòng chảy.',
    love: 'Tình yêu tùy duyên, thuận theo tự nhiên. Cởi mở và chấp nhận.',
    finance: 'Đầu tư theo thị trường. Không cố chấp, biết thay đổi chiến lược.',
    health: 'Sức khỏe ổn, nếu thay đổi môi trường sống sẽ tốt hơn.',
    advice: 'Biết tùy thời mà hành động. Cứng nhắc là thất bại, linh hoạt là thành công.' },
  { number: 18, nameVN: 'Sơn Phong Cổ', nameHV: '蠱', upper: 6, lower: 4, lines: [1, 1, 0, 1, 0, 0],
    meaning: 'Quẻ Cổ tượng trưng cho sự mục nát, hỏng hóc cần sửa chữa. Gió dưới núi, ứ đọng. Cần dọn dẹp, cải tổ.',
    career: 'Công việc trì trệ, cần cải tổ. Sửa sai, thay đổi phương pháp. Cơ hội cho người dám thay đổi.',
    love: 'Quan hệ có vấn đề cần giải quyết. Dọn dẹp những hiểu lầm cũ.',
    finance: 'Thua lỗ do quản lý kém. Cần tái cơ cấu lại tài chính.',
    health: 'Bệnh mãn tính, cần điều trị dứt điểm. Dọn dẹp cơ thể và tâm hồn.',
    advice: 'Đối diện với sự thật, dũng cảm sửa sai. Sửa mình trước khi sửa người.' },
  { number: 19, nameVN: 'Địa Trạch Lâm', nameHV: '臨', upper: 7, lower: 1, lines: [0, 1, 1, 0, 0, 0],
    meaning: 'Quẻ Lâm tượng trưng cho sự tiến gần, giám sát. Đất trên đầm, gần gũi với dân. Nhà lãnh đạo gần dân.',
    career: 'Cơ hội thăng tiến, được giao trọng trách. Lãnh đạo tốt, được lòng cấp dưới.',
    love: 'Tình cảm gần gũi, gắn bó. Quan hệ tiến triển tốt đẹp.',
    finance: 'Kinh doanh phát đạt. Quản lý tài chính hiệu quả.',
    health: 'Sức khỏe tiến triển tốt. Bệnh tật được kiểm soát.',
    advice: 'Hãy gần gũi, quan tâm đến người xung quanh. Lãnh đạo bằng tình thương và sự thấu hiểu.' },
  { number: 20, nameVN: 'Phong Địa Quan', nameHV: '觀', upper: 4, lower: 7, lines: [0, 0, 0, 1, 1, 0],
    meaning: 'Quẻ Quan tượng trưng cho sự quan sát, chiêm nghiệm. Gió trên đất, thổi khắp nơi. Quan sát để hiểu rõ bản chất.',
    career: 'Cần quan sát, tìm hiểu trước khi hành động. Học hỏi kinh nghiệm từ người đi trước.',
    love: 'Tìm hiểu đối phương kỹ càng trước khi tiến tới. Đừng vội vàng.',
    finance: 'Quan sát thị trường trước khi đầu tư. Đừng vội vàng theo đám đông.',
    health: 'Sức khỏe cần chú ý các dấu hiệu bất thường. Khám sức khỏe định kỳ.',
    advice: 'Quan sát kỹ lưỡng trước khi hành động. Trí tuệ đến từ sự chiêm nghiệm.' },
  { number: 21, nameVN: 'Hỏa Lôi Phệ Hạp', nameHV: '噬嗑', upper: 2, lower: 3, lines: [0, 0, 1, 1, 0, 1],
    meaning: 'Quẻ Phệ Hạp tượng trưng cho việc xử lý trở ngại. Lửa trên sấm, ánh sáng xua tan bóng tối. Nhai nghiến vật cản.',
    career: 'Cần quyết đoán giải quyết khó khăn. Đối mặt với thử thách bằng sức mạnh.',
    love: 'Xử lý mâu thuẫn, người thứ ba. Đối diện trực tiếp với vấn đề.',
    finance: 'Thu hồi nợ, giải quyết tranh chấp tài chính.',
    health: 'Có thể phải phẫu thuật hoặc can thiệp y tế. Xử lý dứt điểm bệnh tật.',
    advice: 'Đối diện với khó khăn, giải quyết triệt để. Không trì hoãn, không né tránh.' },
  { number: 22, nameVN: 'Sơn Hỏa Bí', nameHV: '賁', upper: 6, lower: 2, lines: [1, 0, 1, 1, 0, 0],
    meaning: 'Quẻ Bí tượng trưng cho vẻ đẹp, trang sức. Lửa dưới núi, ánh sáng lung linh. Trang trí, làm đẹp, văn hóa.',
    career: 'Chú trọng hình ảnh, thương hiệu. Kinh doanh liên quan đến nghệ thuật, làm đẹp rất tốt.',
    love: 'Tình yêu lãng mạn, đẹp đẽ. Chú trọng vẻ bề ngoài và sự hòa hợp.',
    finance: 'Đầu tư vào hình ảnh, thương hiệu. Ngành làm đẹp sinh lời.',
    health: 'Sức khỏe cần chú ý về mặt thẩm mỹ.',
    advice: 'Đẹp là tốt, nhưng đừng quá chú trọng hình thức. Cái đẹp bền vững đến từ bên trong.' },
  { number: 23, nameVN: 'Sơn Địa Bác', nameHV: '剝', upper: 6, lower: 7, lines: [0, 0, 0, 1, 0, 0],
    meaning: 'Quẻ Bác tượng trưng cho sự sụp đổ, bóc tách. Núi trên đất, đá lở. Mọi thứ đang bị bào mòn, suy tàn.',
    career: 'Suy thoái, mất việc, giáng chức. Cần bảo vệ vị trí của mình. Không nên làm gì lớn.',
    love: 'Tình yêu rạn nứt, đổ vỡ. Cần giữ gìn những gì còn lại.',
    finance: 'Thua lỗ nặng, phá sản. Cắt lỗ, bảo toàn vốn.',
    health: 'Sức khỏe suy giảm nghiêm trọng. Cần điều trị ngay.',
    advice: 'Chấp nhận mất mát, giữ gìn những gì còn lại. Sau cơn mưa trời lại sáng.' },
  { number: 24, nameVN: 'Địa Lôi Phục', nameHV: '復', upper: 7, lower: 3, lines: [0, 0, 1, 0, 0, 0],
    meaning: 'Quẻ Phục tượng trưng cho sự hồi phục, quay lại. Sấm dưới đất, mùa đông qua xuân tới. Mọi thứ đang dần hồi sinh.',
    career: 'Khó khăn sắp qua, cơ hội mới đang đến. Phục hồi sau suy thoái. Tìm lại hướng đi.',
    love: 'Tình cũ không rủ cũng tới. Hàn gắn, làm lành.',
    finance: 'Khủng hoảng qua đi, tài chính dần ổn định. Đầu tư trở lại.',
    health: 'Bệnh tật thuyên giảm. Phục hồi sức khỏe tốt.',
    advice: 'Sau cơn mưa trời lại sáng. Hãy đứng dậy sau vấp ngã. Lạc quan lên.' },
  { number: 25, nameVN: 'Thiên Lôi Vô Vọng', nameHV: '无妄', upper: 0, lower: 3, lines: [0, 0, 1, 1, 1, 1],
    meaning: 'Quẻ Vô Vọng tượng trưng cho sự ngay thẳng, không vọng tưởng. Sấm dưới trời, tự nhiên mà động. Hãy hành động chân thành, đừng mơ tưởng xa vời.',
    career: 'Thành công nhờ sự chân thật, không gian dối. Tránh mưu mô, tiểu xảo.',
    love: 'Tình yêu trong sáng, chân thành. Tình cảm tự nhiên, không gượng ép.',
    finance: 'Đầu tư chân chính sẽ sinh lời. Tránh đầu cơ, lừa đảo.',
    health: 'Sức khỏe tự nhiên tốt. Tránh can thiệp y tế không cần thiết.',
    advice: 'Hãy sống chân thật, đừng vọng tưởng. Người ngay thẳng sẽ gặp may mắn.' },
  { number: 26, nameVN: 'Sơn Thiên Đại Súc', nameHV: '大畜', upper: 6, lower: 0, lines: [1, 1, 1, 1, 0, 0],
    meaning: 'Quẻ Đại Súc tượng trưng cho sự tích lũy lớn. Núi chứa trời, tài năng tiềm ẩn. Tích trữ năng lượng cho việc lớn.',
    career: 'Tích lũy kinh nghiệm, chờ thời cơ. Sức mạnh tiềm ẩn, chuẩn bị cho đại sự.',
    love: 'Tình cảm sâu sắc nhưng kín đáo. Chờ thời điểm thích hợp để bộc lộ.',
    finance: 'Tiết kiệm lớn, đầu tư dài hạn. Tích trữ tài sản có giá trị.',
    health: 'Sức khỏe tốt, tích trữ năng lượng. Tập luyện thể thao đều đặn.',
    advice: 'Học cách tích lũy và chờ đợi. Đại sự cần có sự chuẩn bị kỹ càng.' },
  { number: 27, nameVN: 'Sơn Lôi Di', nameHV: '頤', upper: 6, lower: 3, lines: [0, 0, 1, 1, 0, 0],
    meaning: 'Quẻ Di tượng trưng cho việc nuôi dưỡng. Sấm dưới núi, rung động nhẹ. Nuôi dưỡng thân tâm, ăn uống điều độ.',
    career: 'Chăm sóc nhân sự, đào tạo. Phát triển nguồn lực. Nuôi dưỡng tài năng trẻ.',
    love: 'Chăm sóc người yêu, vun đắp quan hệ. Tình cảm cần được nuôi dưỡng hàng ngày.',
    finance: 'Chi tiêu cho giáo dục, đào tạo. Đầu tư vào con người.',
    health: 'Rất tốt, chú ý dinh dưỡng và nghỉ ngơi. Ăn uống điều độ.',
    advice: 'Nuôi dưỡng thân tâm. Đầu tư vào bản thân là đầu tư khôn ngoan nhất.' },
  { number: 28, nameVN: 'Trạch Phong Đại Quá', nameHV: '大過', upper: 1, lower: 4, lines: [1, 1, 0, 0, 1, 1],
    meaning: 'Quẻ Đại Quá tượng trưng cho sự thái quá, vượt mức. Đầm trên gió, nước dâng tràn. Mọi thứ vượt quá giới hạn.',
    career: 'Có biến động lớn, thay đổi đột ngột. Cần bình tĩnh xử lý, đừng thái quá.',
    love: 'Tình yêu cuồng nhiệt quá mức. Cần tiết chế cảm xúc.',
    finance: 'Chi tiêu vượt mức. Đầu tư mạo hiểm. Cần kiểm soát.',
    health: 'Bệnh nặng, khẩn cấp. Cần cấp cứu kịp thời.',
    advice: 'Tránh thái quá, giữ mọi thứ ở mức vừa phải. Cực thịnh thì suy.' },
  { number: 29, nameVN: 'Thuần Khảm', nameHV: '坎', upper: 5, lower: 5, lines: [0, 1, 0, 0, 1, 0],
    meaning: 'Quẻ Thuần Khảm tượng trưng cho nước, nguy hiểm. Nước chảy không ngừng, lòng sông sâu. Vượt qua thử thách bằng trí tuệ.',
    career: 'Nhiều khó khăn, thử thách. Cần thận trọng và kiên trì. Nước chảy đá mòn.',
    love: 'Tình yêu trắc trở, nhiều thử thách. Cả hai cần vượt qua cùng nhau.',
    finance: 'Nguy hiểm về tài chính. Cẩn thận nợ nần, lừa đảo.',
    health: 'Bệnh tật, nguy hiểm đến tính mạng. Cần điều trị tích cực.',
    advice: 'Đối diện với nguy hiểm bằng lòng can đảm. Nguy hiểm nhất là không biết mình đang gặp nguy.' },
  { number: 30, nameVN: 'Thuần Ly', nameHV: '離', upper: 2, lower: 2, lines: [1, 0, 1, 1, 0, 1],
    meaning: 'Quẻ Thuần Ly tượng trưng cho lửa, ánh sáng, sự rõ ràng. Lửa soi sáng, nhưng cũng có thể thiêu đốt. Nhờ vào trí tuệ mà thành công.',
    career: 'Công việc thuận lợi, có danh tiếng. Ngành truyền thông, giáo dục, nghệ thuật tốt.',
    love: 'Tình yêu nồng cháy, rõ ràng. Có thể yêu xa, yêu qua mạng.',
    finance: 'Kinh doanh liên quan đến ánh sáng, nhiệt, năng lượng tốt.',
    health: 'Chú ý bệnh về mắt, tim mạch. Cần nghỉ ngơi, tránh căng thẳng.',
    advice: 'Ánh sáng của trí tuệ sẽ soi đường cho bạn. Hãy sáng suốt trong mọi quyết định.' },
  { number: 31, nameVN: 'Trạch Sơn Hàm', nameHV: '咸', upper: 1, lower: 6, lines: [1, 0, 0, 0, 1, 1],
    meaning: 'Quẻ Hàm tượng trưng cho sự cảm ứng, thu hút. Đầm trên núi, nước thấm vào đá. Sự hấp dẫn tự nhiên giữa nam và nữ.',
    career: 'Cảm ứng tốt với đồng nghiệp, đối tác. Việc giao tiếp, đàm phán thuận lợi.',
    love: 'Tình yêu từ cái nhìn đầu tiên. Sự rung động tự nhiên, hấp dẫn mãnh liệt.',
    finance: 'Hợp tác tốt, ký kết hợp đồng thuận lợi.',
    health: 'Sức khỏe tốt, còn tràn đầy năng lượng.',
    advice: 'Hãy lắng nghe trái tim mình. Sự rung động chân thành là khởi đầu của mọi điều tốt đẹp.' },
  { number: 32, nameVN: 'Lôi Phong Hằng', nameHV: '恆', upper: 3, lower: 4, lines: [1, 1, 0, 0, 0, 1],
    meaning: 'Quẻ Hằng tượng trưng cho sự bền vững, lâu dài. Sấm trên gió, cùng nhau tồn tại. Kiên trì, giữ vững lập trường.',
    career: 'Thành công bền vững nhờ kiên trì. Giữ vững hướng đi, đừng dao động.',
    love: 'Tình yêu bền vững, lâu dài. Chung thủy, chung tình.',
    finance: 'Đầu tư dài hạn sinh lời đều đặn. Kiên nhẫn chờ đợi lợi nhuận.',
    health: 'Sức khỏe ổn định lâu dài. Duy trì thói quen tốt.',
    advice: 'Kiên trì là chìa khóa của thành công. Có công mài sắt có ngày nên kim.' },
  { number: 33, nameVN: 'Thiên Sơn Độn', nameHV: '遯', upper: 0, lower: 6, lines: [1, 0, 0, 1, 1, 1],
    meaning: 'Quẻ Độn tượng trưng cho sự rút lui, ẩn náu. Núi cao trời xa, lui về ở ẩn. Biết lúc nên tiến, lúc nên lùi.',
    career: 'Nên tạm rút lui, tránh áp lực. Giữ sức, chờ thời cơ khác. Đừng cố chấp.',
    love: 'Tạm xa nhau một thời gian. Khoảng cách giúp hai người hiểu nhau hơn.',
    finance: 'Rút vốn, tránh thua lỗ. Gửi tiền vào nơi an toàn.',
    health: 'Cần nghỉ ngơi, tránh làm việc quá sức. Tĩnh dưỡng.',
    advice: 'Đôi khi lùi là để tiến xa hơn. Biết thời thế là người khôn ngoan.' },
  { number: 34, nameVN: 'Lôi Thiên Đại Tráng', nameHV: '大壯', upper: 3, lower: 0, lines: [1, 1, 1, 0, 0, 1],
    meaning: 'Quẻ Đại Tráng tượng trưng cho sức mạnh to lớn. Sấm trên trời, uy lực mạnh mẽ. Sức mạnh đang ở đỉnh cao.',
    career: 'Sức mạnh, uy quyền đang ở đỉnh cao. Tấn công mạnh mẽ, giành chiến thắng.',
    love: 'Tình yêu mãnh liệt, cuồng nhiệt. Người chủ động, mạnh mẽ.',
    finance: 'Lợi nhuận lớn từ các quyết định táo bạo. Nhưng đừng quá tham.',
    health: 'Sức khỏe đỉnh cao, thể lực dồi dào.',
    advice: 'Có sức mạnh nhưng đừng lạm dụng. Người mạnh nhất là người biết kiềm chế sức mạnh.' },
  { number: 35, nameVN: 'Hỏa Địa Tấn', nameHV: '晉', upper: 2, lower: 7, lines: [0, 0, 0, 1, 0, 1],
    meaning: 'Quẻ Tấn tượng trưng cho sự tiến lên, phát triển. Lửa trên đất, mặt trời mọc. Ngày mới với nhiều hứa hẹn.',
    career: 'Thăng tiến nhanh chóng. Được cấp trên trọng dụng. Cơ hội vàng để phát triển.',
    love: 'Tình yêu tiến triển tốt, có thể tiến tới hôn nhân.',
    finance: 'Tài lộc tăng tiến. Đầu tư sinh lời nhanh.',
    health: 'Sức khỏe tiến bộ. Bệnh tật thuyên giảm rõ rệt.',
    advice: 'Tiến lên không ngừng. Cơ hội đang chờ bạn phía trước.' },
  { number: 36, nameVN: 'Địa Hỏa Minh Di', nameHV: '明夷', upper: 7, lower: 2, lines: [1, 0, 1, 0, 0, 0],
    meaning: 'Quẻ Minh Di tượng trưng cho ánh sáng bị che khuất. Đất trên lửa, ban ngày thành đêm. Gặp khó khăn nhưng không vĩnh viễn.',
    career: 'Bị che mờ, khuất lấp. Có người gièm pha. Cần nhẫn nại chờ thời.',
    love: 'Tình yêu bị thử thách, hiểu lầm. Cần thời gian để sáng tỏ.',
    finance: 'Suy thoái, khó khăn. Tránh đầu tư mới.',
    health: 'Sức khỏe xuống, cần khám bệnh kỹ lưỡng.',
    advice: 'Dù ánh sáng bị che khuất, mặt trời vẫn còn đó. Kiên nhẫn chờ thời cơ.' },
  { number: 37, nameVN: 'Phong Hỏa Gia Nhân', nameHV: '家人', upper: 4, lower: 2, lines: [1, 0, 1, 1, 1, 0],
    meaning: 'Quẻ Gia Nhân tượng trưng cho gia đình, người trong nhà. Gió trên lửa, lửa lan theo gió. Hạnh phúc gia đình lan tỏa.',
    career: 'Tốt cho kinh doanh gia đình. Làm việc trong môi trường thân thuộc, tin cậy.',
    love: 'Gia đình hạnh phúc, êm ấm. Tình cảm gia đình là trên hết.',
    finance: 'Quản lý tài chính gia đình tốt. Kinh doanh từ gia đình.',
    health: 'Mọi người trong nhà đều khỏe mạnh. Chăm sóc sức khỏe cho cả nhà.',
    advice: 'Gia đình là nền tảng của mọi thành công. Hãy trân trọng người thân.' },
  { number: 38, nameVN: 'Hỏa Trạch Khuê', nameHV: '睽', upper: 2, lower: 1, lines: [0, 1, 1, 1, 0, 1],
    meaning: 'Quẻ Khuê tượng trưng cho sự chia ly, mâu thuẫn. Lửa trên đầm, nước với lửa không hợp. Hai bên không đồng thuận.',
    career: 'Xung đột, chia rẽ trong tập thể. Cần tìm điểm chung, tránh đối đầu.',
    love: 'Mâu thuẫn, chia tay. Hai người không còn chung hướng.',
    finance: 'Đối tác làm ăn bất hòa. Cần minh bạch, rõ ràng.',
    health: 'Bệnh về mắt, thần kinh. Cần thư giãn, tránh căng thẳng.',
    advice: 'Đôi khi khác biệt là tốt. Tìm điểm chung, chấp nhận sự khác biệt.' },
  { number: 39, nameVN: 'Thủy Sơn Kiển', nameHV: '蹇', upper: 5, lower: 6, lines: [1, 0, 0, 0, 1, 0],
    meaning: 'Quẻ Kiển tượng trưng cho sự khó khăn, trắc trở. Nước trên núi, suối chảy khó khăn. Gian nan, vất vả.',
    career: 'Gặp nhiều khó khăn, trở ngại. Cần nhẫn nại và kiên trì vượt qua.',
    love: 'Đường tình lận đận, nhiều trắc trở. Cần thời gian và sự kiên nhẫn.',
    finance: 'Khó khăn tài chính, nợ nần. Cần thắt lưng buộc bụng.',
    health: 'Bệnh tật kéo dài, khó chữa. Cần kiên nhẫn điều trị.',
    advice: 'Gian nan rồi sẽ qua. Núi cao rồi cũng có đường lên.' },
  { number: 40, nameVN: 'Lôi Thủy Giải', nameHV: '解', upper: 3, lower: 5, lines: [0, 1, 0, 0, 0, 1],
    meaning: 'Quẻ Giải tượng trưng cho sự giải thoát, cởi mở. Sấm trên nước, mưa đổ giải hạn. Mọi khó khăn được tháo gỡ.',
    career: 'Khó khăn tan biến, mọi việc suôn sẻ. Giải quyết được vấn đề tồn đọng.',
    love: 'Mọi hiểu lầm được hóa giải. Quan hệ trở nên tốt đẹp hơn.',
    finance: 'Nợ nần được giải quyết. Đầu tư bắt đầu sinh lời.',
    health: 'Bệnh tật thuyên giảm, khỏi bệnh. Thoát khỏi tình trạng nguy kịch.',
    advice: 'Vấn đề nào rồi cũng có cách giải quyết. Hãy lạc quan và hành động.' },
  { number: 41, nameVN: 'Sơn Trạch Tổn', nameHV: '損', upper: 6, lower: 1, lines: [0, 1, 1, 1, 0, 0],
    meaning: 'Quẻ Tổn tượng trưng cho sự tổn thất, hy sinh. Núi trên đầm, nước trong núi giảm. Mất mát, hao tổn.',
    career: 'Có mất mát, hy sinh. Nhưng sự hy sinh sẽ được đền đáp xứng đáng.',
    love: 'Hy sinh vì tình yêu. Có thể là chia tay để người kia hạnh phúc.',
    finance: 'Thua lỗ, mất mát tài sản. Cắt lỗ, chấp nhận hy sinh lợi nhuận ngắn hạn.',
    health: 'Sức khỏe giảm sút, cần bồi bổ.',
    advice: 'Có mất có được. Đôi khi phải hy sinh để đạt được điều tốt đẹp hơn.' },
  { number: 42, nameVN: 'Phong Lôi Ích', nameHV: '益', upper: 4, lower: 3, lines: [0, 0, 1, 1, 1, 0],
    meaning: 'Quẻ Ích tượng trưng cho sự gia tăng, lợi ích. Gió trên sấm, sấm mạnh nhờ gió. Được lợi, có thêm sức mạnh.',
    career: 'Được thăng tiến, tăng lương. Công việc phát triển thuận lợi.',
    love: 'Tình cảm ngày càng gắn bó. Gia đình thêm thành viên mới.',
    finance: 'Lợi nhuận tăng, thu nhập cao. Đầu tư về sau càng tốt.',
    health: 'Sức khỏe cải thiện, ngày càng tốt hơn.',
    advice: 'Làm việc tốt, ích nước lợi nhà. Hãy chia sẻ lợi ích với mọi người.' },
  { number: 43, nameVN: 'Trạch Thiên Quải', nameHV: '夬', upper: 1, lower: 0, lines: [1, 1, 1, 1, 1, 0],
    meaning: 'Quẻ Quải tượng trưng cho sự quyết đoán, dứt khoát. Đầm trên trời, nước tràn. Cần hành động dứt khoát, cắt bỏ.',
    career: 'Đưa ra quyết định quan trọng. Cắt bỏ những gì không cần thiết. Dứt khoát, không do dự.',
    love: 'Quyết định tình cảm dứt khoát. Kết thúc hoặc tiến tới, không lưng chừng.',
    finance: 'Thanh lý tài sản, thu hồi vốn. Dứt điểm các khoản nợ.',
    health: 'Phẫu thuật, can thiệp y tế dứt điểm. Cắt bỏ khối u.',
    advice: 'Hãy dứt khoát quyết định. Do dự là chết.' },
  { number: 44, nameVN: 'Thiên Phong Cấu', nameHV: '姤', upper: 0, lower: 4, lines: [1, 1, 0, 1, 1, 1],
    meaning: 'Quẻ Cấu tượng trưng cho sự gặp gỡ bất ngờ. Gió trên trời, thổi khắp nơi. Gặp gỡ tình cờ nhưng định mệnh.',
    career: 'Có cơ hội mới, người mới xuất hiện. Mở ra hướng đi bất ngờ.',
    love: 'Gặp lại người cũ hoặc gặp người mới bất ngờ. Duyên phận tình cờ.',
    finance: 'Cơ hội đầu tư bất ngờ. Lợi nhuận từ việc không ngờ tới.',
    health: 'Bệnh đến bất ngờ. Cần chú ý phòng bệnh hơn chữa bệnh.',
    advice: 'Mọi cuộc gặp đều có duyên phận. Đón nhận cơ hội mới với tâm thế cởi mở.' },
  { number: 45, nameVN: 'Trạch Địa Tụy', nameHV: '萃', upper: 1, lower: 7, lines: [0, 0, 0, 0, 1, 1],
    meaning: 'Quẻ Tụy tượng trưng cho sự tụ họp, quần tụ. Đầm trên đất, nước tụ lại. Mọi người tụ họp, đoàn kết.',
    career: 'Tụ họp nhân tài, xây dựng đội ngũ. Cơ hội hợp tác, liên kết.',
    love: 'Gặp gỡ trong các buổi tụ tập, hội hè. Tình yêu từ bạn bè.',
    finance: 'Góp vốn làm ăn. Huy động vốn từ nhiều nguồn.',
    health: 'Sức khỏe tốt nhờ cộng đồng, tập thể.',
    advice: 'Đoàn kết, tụ họp là sức mạnh. Một cây làm chẳng nên non.' },
  { number: 46, nameVN: 'Địa Phong Thăng', nameHV: '升', upper: 7, lower: 4, lines: [1, 1, 0, 0, 0, 0],
    meaning: 'Quẻ Thăng tượng trưng cho sự đi lên, thăng tiến. Gió dưới đất, đất nâng gió lên. Từ từ đi lên, tiến bộ vững chắc.',
    career: 'Thăng quan tiến chức. Công danh sự nghiệp lên cao. Mọi việc đều tiến triển.',
    love: 'Tình yêu đi lên, có thể tiến tới hôn nhân.',
    finance: 'Tài chính cải thiện, thu nhập tăng. Đầu tư từ từ sẽ lời.',
    health: 'Sức khỏe hồi phục, đi lên. Ngày càng tốt hơn.',
    advice: 'Tiến lên từng bước. Kiên trì và vững chắc, đỉnh cao đang chờ.' },
  { number: 47, nameVN: 'Trạch Thủy Khốn', nameHV: '困', upper: 1, lower: 5, lines: [0, 1, 0, 0, 1, 1],
    meaning: 'Quẻ Khốn tượng trưng cho sự khốn đốn, kiệt quệ. Đầm trên nước, nước cạn khô. Kiệt sức, túng quẫn.',
    career: 'Khốn đốn, bế tắc. Mệt mỏi, áp lực. Cần giữ vững tinh thần.',
    love: 'Tình yêu trong cảnh khó khăn, tuyệt vọng. Hoặc yêu người không yêu mình.',
    finance: 'Khánh kiệt, nợ nần chồng chất. Cần vay mượn để xoay sở.',
    health: 'Sức khỏe suy kiệt, bệnh tật. Cần nghỉ ngơi và điều trị.',
    advice: 'Khốn đốn rồi sẽ qua. Cùng cực sinh biến, giữ vững niềm tin.' },
  { number: 48, nameVN: 'Thủy Phong Tỉnh', nameHV: '井', upper: 5, lower: 4, lines: [1, 1, 0, 0, 1, 0],
    meaning: 'Quẻ Tỉnh tượng trưng cho giếng nước, nguồn sống. Gió dưới nước, giếng khơi mạch ngầm. Nguồn tài nguyên tiềm ẩn.',
    career: 'Có nguồn lực tiềm ẩn, cần khai thác. Công việc ổn định, lâu dài.',
    love: 'Tình yêu bền vững như giếng nước. Lặng lẽ mà sâu sắc.',
    finance: 'Nguồn thu ổn định. Đầu tư khai thác tài nguyên, bất động sản.',
    health: 'Sức khỏe bình thường. Nên uống nhiều nước, chú ý thận.',
    advice: 'Giếng càng khơi càng sâu. Hãy khám phá tiềm năng của bản thân.' },
  { number: 49, nameVN: 'Trạch Hỏa Cách', nameHV: '革', upper: 1, lower: 2, lines: [1, 0, 1, 0, 1, 1],
    meaning: 'Quẻ Cách tượng trưng cho sự thay đổi, cách mạng. Đầm trên lửa, nước với lửa xung đột. Cần thay đổi triệt để.',
    career: 'Thay đổi lớn trong công việc. Chuyển việc, đổi nghề, cải tổ công ty.',
    love: 'Thay đổi tình cảm, có thể là chia tay hoặc tái hôn.',
    finance: 'Cần thay đổi chiến lược đầu tư. Cắt lỗ, đầu tư mới.',
    health: 'Cần thay đổi lối sống. Bỏ thuốc lá, rượu bia.',
    advice: 'Hãy dũng cảm thay đổi. Cái cũ mất đi, cái mới sẽ tốt hơn.' },
  { number: 50, nameVN: 'Hỏa Phong Đỉnh', nameHV: '鼎', upper: 2, lower: 4, lines: [1, 1, 0, 1, 0, 1],
    meaning: 'Quẻ Đỉnh tượng trưng cho đỉnh cao, văn minh. Lửa trên gió, nung nấu đồ đồng. Nấu chín thức ăn, phát triển văn hóa.',
    career: 'Xây dựng sự nghiệp vững chắc. Tạo dựng uy tín, thương hiệu. Lãnh đạo tài ba.',
    love: 'Tình yêu chín muồi, sẵn sàng cho hôn nhân. Xây dựng tổ ấm.',
    finance: 'Xây dựng cơ đồ. Đầu tư dài hạn, vững chắc.',
    health: 'Sức khỏe tốt, cơ thể cân bằng.',
    advice: 'Xây dựng sự nghiệp từ nền tảng vững chắc. Đỉnh cao không đến trong một ngày.' },
  { number: 51, nameVN: 'Thuần Chấn', nameHV: '震', upper: 3, lower: 3, lines: [0, 0, 1, 0, 0, 1],
    meaning: 'Quẻ Thuần Chấn tượng trưng cho sấm sét, sự thức tỉnh. Sấm đùng đùng, gây kinh hoàng. Nhưng cũng mang đến mưa mới.',
    career: 'Có biến động mạnh, thay đổi đột ngột. Cần tỉnh táo và quyết đoán.',
    love: 'Xuất hiện người thứ ba hoặc tin tức bất ngờ. Cần bình tĩnh xử lý.',
    finance: 'Thị trường biến động mạnh. Cơ hội cho người dám chấp nhận rủi ro.',
    health: 'Sốc, tai nạn bất ngờ. Cẩn thận xe cộ, điện giật.',
    advice: 'Sấm sét chỉ là nhất thời. Giữ bình tĩnh, mọi việc sẽ qua.' },
  { number: 52, nameVN: 'Thuần Cấn', nameHV: '艮', upper: 6, lower: 6, lines: [1, 0, 0, 1, 0, 0],
    meaning: 'Quẻ Thuần Cấn tượng trưng cho núi, sự dừng lại. Hai núi chồng lên nhau, vững chãi. Biết dừng đúng lúc.',
    career: 'Nên dừng lại, suy xét. Đừng tiến tiếp. Giữ vững vị trí hiện tại.',
    love: 'Tạm dừng, suy nghĩ về mối quan hệ. Có thể là chia tay.',
    finance: 'Ngừng đầu tư, quan sát thị trường. Giữ tiền mặt.',
    health: 'Cần nghỉ ngơi, dừng các hoạt động mạnh.',
    advice: 'Núi cao biết dừng. Biết đủ là đủ, biết dừng là khôn.' },
  { number: 53, nameVN: 'Phong Sơn Tiệm', nameHV: '漸', upper: 4, lower: 6, lines: [1, 0, 0, 1, 1, 0],
    meaning: 'Quẻ Tiệm tượng trưng cho sự tiến triển từ từ. Gió trên núi, cây cối từ từ lớn. Việc nhỏ làm dần sẽ thành công lớn.',
    career: 'Tiến chậm mà chắc. Học hỏi từng ngày. Xây dựng dần dần.',
    love: 'Tình yêu phát triển chậm rãi. Từng bước tìm hiểu, xây dựng niềm tin.',
    finance: 'Đầu tư dài hạn. Góp gió thành bão.',
    health: 'Sức khỏe cải thiện từ từ. Kiên trì luyện tập.',
    advice: 'Kiên nhẫn từng bước. Không có thành công nào đến ngay lập tức.' },
  { number: 54, nameVN: 'Lôi Trạch Quy Muội', nameHV: '歸妹', upper: 3, lower: 1, lines: [0, 1, 1, 0, 0, 1],
    meaning: 'Quẻ Quy Muội tượng trưng cho việc gả chồng, kết hôn. Sấm trên đầm, rung động. Hôn nhân, sự kết hợp.',
    career: 'Hợp tác, liên doanh. Kết hợp nguồn lực. Có thể thay đổi môi trường làm việc.',
    love: 'Hôn nhân, kết hôn. Trai gái nên duyên. Rất tốt cho tình cảm.',
    finance: 'Kết hợp tài chính. Góp vốn kinh doanh với người thân.',
    health: 'Sức khỏe ổn định. Có thể thay đổi chỗ ở, môi trường.',
    advice: 'Kết hợp là sức mạnh. Đôi lứa hòa hợp sẽ tạo nên điều tốt đẹp.' },
  { number: 55, nameVN: 'Lôi Hỏa Phong', nameHV: '豐', upper: 3, lower: 2, lines: [1, 0, 1, 0, 0, 1],
    meaning: 'Quẻ Phong tượng trưng cho sự phong phú, thịnh vượng. Sấm trên lửa, ánh sáng và âm thanh. Mùa màng bội thu, giàu có.',
    career: 'Phát triển thịnh vượng. Mùa gặt hái thành công. Mọi việc đều tốt đẹp.',
    love: 'Tình yêu sung mãn, hạnh phúc. Cuộc sống tình cảm phong phú.',
    finance: 'Đại tài, giàu có. Lợi nhuận lớn, tài chính dồi dào.',
    health: 'Sức khỏe tốt, cuộc sống đầy đủ, vui vẻ.',
    advice: 'Tận hưởng thành công nhưng đừng quá phung phí. Giữ gìn những gì đã đạt được.' },
  { number: 56, nameVN: 'Hỏa Sơn Lữ', nameHV: '旅', upper: 2, lower: 6, lines: [1, 0, 0, 1, 0, 1],
    meaning: 'Quẻ Lữ tượng trưng cho sự đi xa, lữ hành. Lửa trên núi, ánh lửa trên đỉnh. Đi xa, ở nhờ, tạm bợ.',
    career: 'Làm việc xa nhà. Công tác, du lịch. Cơ hội từ nơi xa.',
    love: 'Yêu xa, tình yêu qua mạng. Người nơi khác đến.',
    finance: 'Kinh doanh xa, buôn bán đường dài. Cơ hội từ nước ngoài.',
    health: 'Chú ý sức khỏe khi đi xa. Bệnh lạ nơi xa.',
    advice: 'Lữ hành là cơ hội trải nghiệm. Học cách thích nghi với môi trường mới.' },
  { number: 57, nameVN: 'Thuần Tốn', nameHV: '巽', upper: 4, lower: 4, lines: [1, 1, 0, 1, 1, 0],
    meaning: 'Quẻ Thuần Tốn tượng trưng cho gió, sự thâm nhập. Gió thổi nhẹ nhàng nhưng thấm sâu. Nhờ mềm dẻo mà thành công.',
    career: 'Thuận lợi nhờ sự mềm dẻo, thích ứng. Thâm nhập thị trường mới. Giao tiếp tốt.',
    love: 'Tình yêu nhẹ nhàng, sâu lắng. Lãng mạn, ngọt ngào.',
    finance: 'Lợi nhuận từ nhiều nguồn nhỏ. Đầu tư phân tán.',
    health: 'Sức khỏe ổn định. Hít thở không khí trong lành tốt cho phổi.',
    advice: 'Nhẹ nhàng nhưng thấm sâu. Gió thổi cỏ lay, kiên trì và dịu dàng.' },
  { number: 58, nameVN: 'Thuần Đoài', nameHV: '兑', upper: 1, lower: 1, lines: [0, 1, 1, 0, 1, 1],
    meaning: 'Quẻ Thuần Đoài tượng trưng cho hồ, niềm vui, sự giao tiếp. Hai hồ nước trong soi sáng lẫn nhau. Hạnh phúc, vui vẻ.',
    career: 'Công việc vui vẻ, hòa đồng. Ngành giao tiếp, ngoại giao, bán hàng tốt.',
    love: 'Hạnh phúc, vui vẻ. Hai người tâm đầu ý hợp, cùng nhau tận hưởng cuộc sống.',
    finance: 'Kinh doanh thuận lợi. Khách hàng hài lòng.',
    health: 'Tinh thần vui vẻ, sức khỏe tốt. Cười mỗi ngày là thuốc bổ.',
    advice: 'Niềm vui lan tỏa. Hãy sống vui vẻ và lan tỏa hạnh phúc cho người khác.' },
  { number: 59, nameVN: 'Phong Thủy Hoán', nameHV: '渙', upper: 4, lower: 5, lines: [0, 1, 0, 1, 1, 0],
    meaning: 'Quẻ Hoán tượng trưng cho sự tan rã, tiêu tan. Gió trên nước, sóng lan xa. Băng tan, rào cản được phá bỏ.',
    career: 'Tan rã, tổ chức giải tán. Nhưng cũng mở ra cơ hội mới. Không nên cố chấp.',
    love: 'Tình yêu tan vỡ. Chia tay, ly hôn. Nhưng sẽ có khởi đầu mới.',
    finance: 'Tài sản phân tán, thất thoát. Cần thu gom, gom lại.',
    health: 'Bệnh lây lan. Cần cách ly và điều trị.',
    advice: 'Có tan ắt có hợp. Chấp nhận mất mát để đón nhận điều mới.' },
  { number: 60, nameVN: 'Thủy Trạch Tiết', nameHV: '節', upper: 5, lower: 1, lines: [0, 1, 1, 0, 1, 0],
    meaning: 'Quẻ Tiết tượng trưng cho sự tiết chế, điều độ. Nước trên đầm, đầm chứa nước vừa phải. Biết tiết chế sẽ bền vững.',
    career: 'Cần tiết chế, đừng quá tham. Quản lý nguồn lực hiệu quả.',
    love: 'Tình yêu có chừng mực. Tiết chế cảm xúc, đừng quá cuồng nhiệt.',
    finance: 'Tiết kiệm, chi tiêu hợp lý. Quản lý ngân sách tốt.',
    health: 'Ăn uống điều độ, sinh hoạt điều độ sẽ khỏe mạnh.',
    advice: 'Mọi thứ đều cần có chừng mực. Thái quá là bất cập.' },
  { number: 61, nameVN: 'Phong Trạch Trung Phu', nameHV: '中孚', upper: 4, lower: 1, lines: [0, 1, 1, 1, 1, 0],
    meaning: 'Quẻ Trung Phu tượng trưng cho lòng thành tín. Gió trên đầm, lan tỏa lòng tin. Trung thực, đáng tin cậy.',
    career: 'Thành công nhờ uy tín. Được đối tác, đồng nghiệp tin tưởng. Ký kết hợp đồng tốt.',
    love: 'Tình yêu chân thành, tin tưởng lẫn nhau. Niềm tin là nền tảng vững chắc.',
    finance: 'Kinh doanh nhờ chữ tín. Uy tín mang lại lợi nhuận.',
    health: 'Sức khỏe tinh thần tốt. Tâm hồn thanh thản, ít lo âu.',
    advice: 'Chữ tín quý hơn vàng. Hãy sống ngay thẳng, trung thực.' },
  { number: 62, nameVN: 'Lôi Sơn Tiểu Quá', nameHV: '小過', upper: 3, lower: 6, lines: [1, 0, 0, 0, 0, 1],
    meaning: 'Quẻ Tiểu Quá tượng trưng cho sự sai sót nhỏ. Sấm trên núi, tiếng vang yếu. Sai lầm nhỏ, cẩn thận sửa chữa.',
    career: 'Sai sót nhỏ trong công việc. Cần kiểm tra kỹ. Cẩn thận từng chi tiết.',
    love: 'Hiểu lầm nhỏ, ghen tuông nhẹ. Cần nói chuyện để làm rõ.',
    finance: 'Sai sót trong tính toán. Cần kiểm tra sổ sách.',
    health: 'Bệnh nhẹ, cảm cúm. Cần nghỉ ngơi.',
    advice: 'Sai lầm nhỏ, sửa ngay kẻo thành lớn. Cẩn trọng từng điều nhỏ.' },
  { number: 63, nameVN: 'Thủy Hỏa Ký Tế', nameHV: '既濟', upper: 5, lower: 2, lines: [1, 0, 1, 0, 1, 0],
    meaning: 'Quẻ Ký Tế tượng trưng cho sự đã hoàn thành. Nước trên lửa, lửa tắt, nước sôi. Mọi việc đã xong, thành công.',
    career: 'Đã hoàn thành mục tiêu. Hái quả ngọt. Nhưng đừng quá tự mãn.',
    love: 'Tình yêu đã đến đích. Hạnh phúc viên mãn.',
    finance: 'Đã thu hồi vốn và lãi. Thành công về tài chính.',
    health: 'Đã khỏi bệnh, hồi phục hoàn toàn.',
    advice: 'Thành công rồi nhưng đừng tự mãn. Mọi việc đều có lúc thịnh suy.' },
  { number: 64, nameVN: 'Hỏa Thủy Vị Tế', nameHV: '未濟', upper: 2, lower: 5, lines: [0, 1, 0, 1, 0, 1],
    meaning: 'Quẻ Vị Tế tượng trưng cho sự chưa hoàn thành. Lửa trên nước, không tương dung. Việc chưa xong, còn dang dở.',
    career: 'Việc còn dang dở, chưa xong. Cần tiếp tục cố gắng. Không nản lòng.',
    love: 'Tình yêu chưa ngỏ lời, chưa thành. Cần thêm thời gian và cố gắng.',
    finance: 'Dự án chưa hoàn thành. Chưa thu hồi vốn. Kiên nhẫn chờ đợi.',
    health: 'Bệnh chưa khỏi hoàn toàn. Cần tiếp tục điều trị.',
    advice: 'Chưa xong không có nghĩa là thất bại. Tiếp tục cố gắng, thành công sẽ đến.' },
];

// ─── LOOKUP ───
export const QUE_LOOKUP = (() => {
  const map = {};
  QUE_64.forEach((q, i) => { map[q.lines.join('')] = i; });
  return map;
})();

// ─── HELPERS ───
export const getLinesFromTrigrams = (upper, lower) => [...TRIGRAM_LINES[lower], ...TRIGRAM_LINES[upper]];

export const findQueIndex = (lines) => QUE_LOOKUP[lines.join('')];

const trigramBinaryToIdx = (bin3) => {
  const map = { 7: 0, 3: 1, 5: 2, 1: 3, 6: 4, 2: 5, 4: 6, 0: 7 };
  return map[bin3] !== undefined ? map[bin3] : 0;
};

// ─── BUILD QUE RESULT ───
export const buildQueResult = (upper, lower, haoDong) => {
  const lines = getLinesFromTrigrams(upper, lower);
  const queChuIdx = findQueIndex(lines);
  const queChu = QUE_64[queChuIdx];
  const thuongQuai = BAT_QUAI[upper];
  const haQuai = BAT_QUAI[lower];

  // Quẻ biến
  let queBien = null;
  if (haoDong >= 0 && haoDong < 6) {
    const bienLines = [...lines];
    bienLines[haoDong] = bienLines[haoDong] === 0 ? 1 : 0;
    const bienIdx = findQueIndex(bienLines);
    if (bienIdx !== undefined) queBien = QUE_64[bienIdx];
  }

  // Hỗ quái (hào 2-3-4 = hạ, 3-4-5 = thượng)
  const hoHa = (lines[1] << 2) | (lines[2] << 1) | (lines[3] << 0);
  const hoThuong = (lines[2] << 2) | (lines[3] << 1) | (lines[4] << 0);
  const hoHaIdx = trigramBinaryToIdx(hoHa);
  const hoThuongIdx = trigramBinaryToIdx(hoThuong);
  const hoLines = getLinesFromTrigrams(hoThuongIdx, hoHaIdx);
  const hoQueIdx = findQueIndex(hoLines);
  const hoQue = hoQueIdx !== undefined ? QUE_64[hoQueIdx] : null;

  return {
    thuongQuai, haQuai,
    haoDong: haoDong + 1,
    lines,
    queChu,
    queBien,
    hoQue,
  };
};

// ─── PHƯƠNG PHÁP 1: Theo âm lịch ───
export const tinhQueTheoAmLich = (lunarYear, lunarMonth, lunarDay) => {
  const upper = ((lunarYear % 8) + 8) % 8;
  const lower = ((lunarMonth % 8) + 8) % 8;
  const haoDong = ((lunarDay - 1) % 6 + 6) % 6;
  const result = buildQueResult(upper, lower, haoDong);
  result.method = 'Âm lịch';
  return result;
};

// ─── PHƯƠNG PHÁP 2: Theo số Julian ───
export const tinhQueTheoJD = (julianDay) => {
  const upper = ((julianDay % 8) + 8) % 8;
  const lower = (Math.floor(julianDay / 8) % 8 + 8) % 8;
  const haoDong = ((julianDay % 6) + 6) % 6;
  const result = buildQueResult(upper, lower, haoDong);
  result.method = 'Julian';
  return result;
};

// ─── PHƯƠNG PHÁP 3: Gieo 3 đồng xu ───
export const gieoQue3DongXu = () => {
  const lines = [];
  let firstChanged = -1;
  for (let i = 0; i < 6; i++) {
    const toss = (Math.random() < 0.5 ? 3 : 2) + (Math.random() < 0.5 ? 3 : 2) + (Math.random() < 0.5 ? 3 : 2);
    if (toss === 6) { lines.push(0); if (firstChanged < 0) firstChanged = i; }
    else if (toss === 7) lines.push(1);
    else if (toss === 8) lines.push(0);
    else if (toss === 9) { lines.push(1); if (firstChanged < 0) firstChanged = i; }
  }
  const haoDong = firstChanged;
  const lowerBin = (lines[5] << 2) | (lines[4] << 1) | (lines[3] << 0);
  const upperBin = (lines[2] << 2) | (lines[1] << 1) | (lines[0] << 0);
  const lower = trigramBinaryToIdx(lowerBin);
  const upper = trigramBinaryToIdx(upperBin);
  const result = buildQueResult(upper, lower, haoDong);
  result.method = '3 đồng xu';
  result.lines = lines;
  return result;
};
